version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: proyectoVerduleria
      DB_USERNAME: postgres
      DB_PASSWORD: gatanovia

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: proyectoVerduleria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gatanovia
