version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .Dockerfile  # Nuevo nombre del archivo Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: proyectoVerduleria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gatanovia
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
